{"name": "用户注册登录查看-预期成功", "status": "broken", "statusDetails": {"message": "AttributeError: 'User' object has no attribute 'list_one_user'", "trace": "self = <testcases.scenario_test.test_kuai_register_login_list.TestRegLogList object at 0x105e6e5e0>\ntestcase_data_kuai = {'except_code': 200, 'except_msg': '查询用户信息成功', 'except_result': True, 'login': {'phone': '13800138000', 'username': '小花平台', 'verificationCode': '123456'}}\n\n    @allure.story(\"用例--注册/登录/查看--预期成功\")\n    @allure.description(\"该用例是针对 注册-登录-查看 场景的测试\")\n    @allure.issue(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"用户注册登录查看-预期成功\")\n    @pytest.mark.multiple\n    # @pytest.mark.usefixtures(\"delete_register_user\")#如果一个方法或者一个class用例想要同时调用多个fixture，可以使用@pytest.mark.usefixture()进行叠加。注意叠加顺序，先执行的放底层，后执行的放上层。\n    def test_user_register_login_update_success(self, testcase_data_kuai):\n        username = testcase_data_kuai[\"login\"][\"username\"]\n        verificationCode = testcase_data_kuai[\"login\"][\"verificationCode\"]\n        phone = testcase_data_kuai[\"login\"][\"phone\"]\n    \n        except_result = testcase_data_kuai[\"except_result\"]\n        except_code = testcase_data_kuai[\"except_code\"]\n        except_msg = testcase_data_kuai[\"except_msg\"]\n    \n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = login_user(phone, verificationCode)\n        step_2(phone)\n        token = result.token\n        logger.info(\"-------------{}\".format(token))\n        assert result.success is True, result.error\n    \n>       result = get_one_user_info(token)\n\ntest_kuai_register_login_list.py:51: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ntoken = 'eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJiNjg0MTE4OTYzMTY0MzY3YjQzZTMwYzhlMGIyN2JlYyIsInN1YiI6IuWwj-iKseW5s-WPsCIsInVzZXJJZCI6MTMsImlhdCI6MTYyODE1MzU3N30.vYKpnjE1ydqo4ltwaf6EkhODoptTeyBICWyPWFouDNo'\n\n    def get_one_user_info(token):\n        \"\"\"\n        获取单个用户信息\n        :param username:  用户名\n        :return: 自定义的关键字返回结果 result\n        \"\"\"\n        result = ResultBase()\n>       res = user.list_one_user(token)\nE       AttributeError: 'User' object has no attribute 'list_one_user'\n\n../../operation/user_kuai.py:40: AttributeError"}, "description": "该用例是针对 注册-登录-查看 场景的测试", "steps": [{"name": "步骤2 ==>> 登录用户", "status": "passed", "parameters": [{"name": "phone", "value": "'13800138000'"}], "start": 1628153577877, "stop": 1628153577877}], "attachments": [{"name": "log", "source": "e4f81b1a-87fa-4f54-b350-f466b5882ef9-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "8a364ce3-ef42-4865-9548-c2da30a604ad-attachment.txt", "type": "text/plain"}], "start": 1628153577789, "stop": 1628153577878, "uuid": "01d2277e-3f9f-456b-849b-e7ffe5e1b078", "historyId": "2f9e2033e857a196e3cfafbf0e3c91fb", "testCaseId": "c78b7fc66a86a49af4c08176ea915368", "fullName": "testcases.scenario_test.test_kuai_register_login_list.TestRegLogList#test_user_register_login_update_success", "labels": [{"name": "feature", "value": "场景：用户注册-用户登录-查看用户"}, {"name": "epic", "value": "针对业务场景的测试"}, {"name": "severity", "value": "critical"}, {"name": "story", "value": "用例--注册/登录/查看--预期成功"}, {"name": "tag", "value": "multiple"}, {"name": "parentSuite", "value": "testcases.scenario_test"}, {"name": "suite", "value": "test_kuai_register_login_list"}, {"name": "subSuite", "value": "TestRegLogList"}, {"name": "host", "value": "zengxiaohua.local"}, {"name": "thread", "value": "11194-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.scenario_test.test_kuai_register_login_list"}], "links": [{"type": "test_case", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应BUG的链接地址"}]}