{"name": "测试数据：【 13200138000，123456，False，1007，用户不存在】", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1001 == 1007", "trace": "self = <testcases.api_test.test_kuai_login.TestUserLogin object at 0x10cdc8520>\nphone = '13200138000', verificationCode = '123456', except_result = False\nexcept_code = 1007, except_msg = '用户不存在'\n\n    @allure.story(\"用例--登录用户\")\n    @allure.description(\"该用例是针对获取用户登录接口的测试\")\n    @allure.issue(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"测试数据：【 {phone}，{verificationCode}，{except_result}，{except_code}，{except_msg}】\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"phone, verificationCode, except_result, except_code, except_msg\",\n                             api_kuai_data[\"test_login_user\"])\n    def test_login_user(self, phone, verificationCode, except_result, except_code, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = login_user(phone, verificationCode)\n        print(\"result:\",result)\n        step_1(phone)\n        assert result.success == except_result, result.error\n        assert result.response.status_code == 200\n        assert result.success == except_result, result.error\n        logger.info(\"code ==>> 期望结果：{}， 实际结果：【 {} 】\".format(except_code, result.response.json().get(\"code\")))\n>       assert result.response.json().get(\"code\") == except_code\nE       assert 1001 == 1007\n\ntest_kuai_login.py:35: AssertionError"}, "description": "该用例是针对获取用户登录接口的测试", "steps": [{"name": "步骤1 ==>> 登录用户", "status": "passed", "parameters": [{"name": "phone", "value": "'13200138000'"}], "start": 1628071033940, "stop": 1628071033940}], "attachments": [{"name": "log", "source": "ed062914-da90-4ad3-b6c6-ba5164c518e3-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "4a94970c-9a0f-4d2a-b4fd-f6598baf3040-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "1950d27f-f4c7-4c95-8025-562f9d09b7e6-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "phone", "value": "'13200138000'"}, {"name": "verificationCode", "value": "'123456'"}, {"name": "except_result", "value": "False"}, {"name": "except_code", "value": "1007"}, {"name": "except_msg", "value": "'用户不存在'"}], "start": 1628071033909, "stop": 1628071033941, "uuid": "294d76a9-dc0b-49e2-8639-f31e640c896f", "historyId": "3932cc63447aeccf4da8002ede2829a0", "testCaseId": "4cf2c2f7c5a680a41fe59cb327f3c0a1", "fullName": "testcases.api_test.test_kuai_login.TestUserLogin#test_login_user", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "用户登录模块"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "story", "value": "用例--登录用户"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_kuai_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "zengxiaohua.local"}, {"name": "thread", "value": "2243-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_kuai_login"}], "links": [{"type": "test_case", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应BUG的链接地址"}]}